### ISSUE TITLE
TypeError: root is null

### ISSUE THREAD

**Issue by ilium007** [safepay/sensor.willyweather#15]
I am confident I have set everything according to the instructions both here and at https://github.com/iammexx/home-assistant-config/tree/master/ui/darksky

I have a UI card displaying the retrieved entities from the WillyWeather 7 day data so I know the API and retrieval is all working.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/732766/133928551-7df1c71b-8eb9-482c-92c6-2dac3d7d021e.png">

I have added the DarkSky js resource to the Lovelace resources config page (after getting a warning about adding it to the card config page:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/732766/133928591-44574962-9b72-4a41-8226-6ce9088091ca.png">

I added the config to the UI in Raw Config Editor:

```
- title: TEST
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.ww_cloud
          - sensor.ww_day_0_icon
          - sensor.ww_day_0_max_temp
          - sensor.ww_day_0_min_temp
          - sensor.ww_day_0_rain
          - sensor.ww_day_0_rain_probability
          - sensor.ww_day_0_summary
          - sensor.ww_day_1_icon
          - sensor.ww_day_1_max_temp
          - sensor.ww_day_1_min_temp
          - sensor.ww_day_1_rain
          - sensor.ww_day_1_rain_probability
          - sensor.ww_day_1_summary
          - sensor.ww_day_2_icon
          - sensor.ww_day_2_max_temp
          - sensor.ww_day_2_min_temp
          - sensor.ww_day_2_rain
          - sensor.ww_day_2_rain_probability
          - sensor.ww_day_2_summary
          - sensor.ww_day_3_icon
          - sensor.ww_day_3_max_temp
          - sensor.ww_day_3_min_temp
          - sensor.ww_day_3_rain
          - sensor.ww_day_3_rain_probability
          - sensor.ww_day_3_summary
          - sensor.ww_day_4_icon
          - sensor.ww_day_4_max_temp
          - sensor.ww_day_4_min_temp
          - sensor.ww_day_4_rain
          - sensor.ww_day_4_rain_probability
          - sensor.ww_day_4_summary
          - sensor.ww_day_5_icon
          - sensor.ww_day_5_max_temp
          - sensor.ww_day_5_min_temp
          - sensor.ww_day_5_rain
          - sensor.ww_day_5_rain_probability
          - sensor.ww_day_5_summary
          - sensor.ww_day_6_icon
          - sensor.ww_day_6_max_temp
          - sensor.ww_day_6_min_temp
          - sensor.ww_day_6_rain
          - sensor.ww_day_6_rain_probability
          - sensor.ww_day_6_summary
          - sensor.ww_dew_point
          - sensor.ww_feels_like
          - sensor.ww_humidity
          - sensor.ww_pressure
          - sensor.ww_rain_last_hour
          - sensor.ww_rain_since_9am
          - sensor.ww_rain_today
          - sensor.ww_temperature
          - sensor.ww_wind_bearing
          - sensor.ww_wind_direction
          - sensor.ww_wind_gust
          - sensor.ww_wind_speed
      - type: custom:dark-sky-weather-card
        entity_current_conditions: sensor.ww_day_0_icon
        entity_current_text: sensor.ww_day_0_summary
        entity_forecast_high_temp_1: sensor.ww_day_1_max_temp
        entity_forecast_high_temp_2: sensor.ww_day_2_max_temp
        entity_forecast_high_temp_3: sensor.ww_day_3_max_temp
        entity_forecast_high_temp_4: sensor.ww_day_4_max_temp
        entity_forecast_high_temp_5: sensor.ww_day_5_max_temp
        entity_forecast_icon_1: sensor.ww_day_0_icon
        entity_forecast_icon_2: sensor.ww_day_1_icon
        entity_forecast_icon_3: sensor.ww_day_2_icon
        entity_forecast_icon_4: sensor.ww_day_3_icon
        entity_forecast_icon_5: sensor.ww_day_4_icon
        entity_forecast_low_temp_1: sensor.ww_day_0_min_temp
        entity_forecast_low_temp_2: sensor.ww_day_1_min_temp
        entity_forecast_low_temp_3: sensor.ww_day_2_min_temp
        entity_forecast_low_temp_4: sensor.ww_day_3_min_temp
        entity_forecast_low_temp_5: sensor.ww_day_4_min_temp
        entity_summary_1: sensor.ww_day_0_summary
        entity_summary_2: sensor.ww_day_1_summary
        entity_summary_3: sensor.ww_day_2_summary
        entity_summary_4: sensor.ww_day_3_summary
        entity_summary_5: sensor.ww_day_4_summary
        entity_temperature: sensor.ww_temperature
        entity_sun: sun.sun
        entity_daytime_high: sensor.ww_day_0_max_temp
        entity_wind_bearing: sensor.ww_wind_bearing
        entity_wind_speed: sensor.ww_wind_speed
        entity_humidity: sensor.ww_humidity
        entity_pressure: sensor.ww_pressure
        entity_apparent_temp: sensor.ww_feels_like
        entity_pop: sensor.ww_day_0_rain_probability
        entity_pop_1: sensor.ww_day_1_rain_probability
        entity_pop_2: sensor.ww_day_2_rain_probability
        entity_pop_3: sensor.ww_day_3_rain_probability
        entity_pop_4: sensor.ww_day_4_rain_probability
        entity_pop_5: sensor.ww_day_5_rain_probability
```

This resulted in the error below

`
2021-09-19 22:59:21 ERROR (MainThread) [frontend.js.latest.202108300] https://homeassistant.xxxxx.dev/local/custom_ui/dark-sky-weather-card.js?v=7.1:709:9 TypeError: root is null`
